### ISSUE TITLE
Windows Manager

### ISSUE THREAD

**Issue by Lunatixz** [PseudoTV/PseudoTV_Manager#1]
@PseudoTV/scripters 

Can we consolidate all forks and branches to this repo for development?

Thanks

**Comment by Lunatixz** [comment]
@computergeek1507 I branched you're Csharp fork, hoping we can consolidate code here and join efforts...

**Comment by xioustic** [comment]
What other forks are we looking to consolidate? I can start merging / shadow branching if a list is provided.

No use including anything massively outdated or unused.
