### ISSUE TITLE
Could we have a list of dependencies?

### ISSUE THREAD

**Issue by bitfed** [PseudoTV/PseudoTV_Manager#2]
I've been trying so stubbornly to get any version of this software to run.  I'm running Windows 10 and am not seeming to have the same experience as others.  What redistributables should I have installed in order to run this?

**Comment by Lunatixz** [comment]
Kodi takes care of all dependencies on its own , The only thing required to install this plugin is my repository.

**Comment by bitfed** [comment]
I'm referring to PseudoTV Manager. I have not been able to get any builds
of it to run on Windows 10. Am I missing something I should have installed?
