### ISSUE TITLE
Python Project / Branch Name

### ISSUE THREAD

**Issue by xioustic** [PseudoTV/PseudoTV_Manager#4]
Why pyPTVL? I'd assume it stands for "Python Pseudo TV Live", which doesn't make a lot of since, since the actual AddOn is in Python which might confuse people.

My original name was pyPTVMan, which I figured was decent enough: "Python PseudoTV Manager". However, since the scope is specifically for PseudoTV Live, I can see changing it to pyPTVLMan.

Overall, none of this in particular rolls off the tongue easily. Should we just make the Python implementation (once it's ready) the new master branch and continue referring to it as PseudoTV Manager?

**Comment by Lunatixz** [comment]
It was a quick branch name, release name doesn't have to reflect the branch name....

**Comment by xioustic** [comment]
Got it, thanks :)
