### ISSUE TITLE
Python: Determine Minimum Viable Functionality for Alpha

### ISSUE THREAD

**Issue by xioustic** [PseudoTV/PseudoTV_Manager#8]
What's our minimum viable functionality for first release? What are the most common workflows (channel types) we're looking to cover?

Thoughts:
- SQLite support (MySQL is desired but could hold off, but I can't personally use this without MySQL support) for Video database
- Settings2 XML readable/writable
- Addons.db support (do we need this right away? what does this accomplish? need to read thru source code to find out)
- UI Implementation using Qt Bindings
- Latest Stable Kodi supported (Jarvis at this time)
- Safely ignore / leave unimplemented channel types and features alone without steamrolling them

**Comment by Lunatixz** [comment]
First release should allow basic channel building for channel types 0-11 formating is pretty basic... once we get something functional we can start adding the more complex channels like Plugins, UPNP and the advanced channel rules.

Addons.db isn't needed... I don't believe it ever provided the functionality @peppy6582 and I were hoping for. We were looking for a simple solution to list all plugins available on a user's kodi instance.

MySQL is top on my list.. both should be easy to implement.

**Comment by xioustic** [comment]
OK, so Addons.db is scratched.
MySQL is a maybe; definitely wrap Sqlite and MySQL in the same set of functions.
Chtypes 0-11:
(0). - Custom Smartplaylist
(1). - TV networks
(2). - Movie Studios
(3). - TV Genre
(4). - Movie Genre
(5). - Mixed TV/Movie Genre
(6). - TV Show
(7). - Directory Channel
(8). - LiveTV, Use with a single video source and matching xmltv EPG data.
(9). - InternetTV, Use with a single video source and no matching EPG data. EPG data is provided manually via settings.
(10). - Youtube Channels
(11). - RSS Feed
